[package]
name = "erfan_command_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
